using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using VRemoteClient.Models.CustomEvents;
using VRemoteClient.Models.Enums;
using VRemoteClient.Utils;
using static VRemoteClient.Models.Enums.KeyboardEnums;
using static VRemoteClient.Utils.Libraries;
using static VRemoteClient.Utils.Libraries.HookApis;

namespace VRemoteClient.Services.KeyboardService
{
    public class GlobalKeyboardHook: IDisposable
    {
        private readonly object _lockObject = new object();
        private bool _disposed;
        private IntPtr _hookID;
        private LowLevelProc _proc;
        public HashSet<IntPtr> _windowsHandle; 
        public event EventHandler<CustomKeyMessageEventArgs> KeyPressed;
        public GlobalKeyboardHook() 
        {
            _disposed = false;
            _hookID = IntPtr.Zero;
            WindowsHandle = new HashSet<IntPtr>();
        }
        public void Start(uint pId)
        {
            _proc = HookCallback;
            _hookID = SetHook(_proc);
        }
        #region Properties
        public HashSet<IntPtr> WindowsHandle
        {
            get
            {
                lock (_lockObject)
                {
                    return _windowsHandle;
                }
            }
            set
            {
                lock (_lockObject)
                {
                    _windowsHandle = value;
                }
            }
        }
        #endregion
        /// <summary>
        /// Starts listening for keyboard events on a specific Form.
        /// </summary>
        /// <param name="handle">The handle of the Form to listen to (use <c>this.Handle</c> in the Form).</param>
        public void AddHook(IntPtr handle)
        {
            lock (_lockObject)
            {
                WindowsHandle.Add(handle);
            }
        }
        /// <summary>
        /// Stops listening for keyboard events on a specific Form.
        /// </summary>
        /// <param name="handle">The handle of the Form to stop listening to (use <c>this.Handle</c> in the Form).</param>
        public void RemoveHook(IntPtr handle)
        {
            lock (_lockObject)
            {
                WindowsHandle.Remove(handle);
            }
        }
        public void Stop()
        {
            if (_hookID != IntPtr.Zero)
            {
                HookApis.UnhookWindowsHookEx(_hookID);
                _hookID = IntPtr.Zero;
            }
        }
        private bool IsHandleFocus(IntPtr handle)
        {
            return WindowApis.GetForegroundWindow() == handle;
        }
        private IntPtr SetHook(LowLevelProc proc)
        {
            using (Process curProcess = Process.GetCurrentProcess())
            using (ProcessModule curModule = curProcess.MainModule)
            {
                ////get specifi windows handle
                //return SetWindowsHookEx(WH_KEYBOARD_LL, proc,
                //    GetModuleHandle(curModule.ModuleName), 0);

                //get all of this process
                return HookApis.SetWindowsHookEx((int)WindowsKeyboardEvent.WH_KEYBOARD_LL, proc,
                    IntPtr.Zero, 0);
            }
        }
        /// <summary>
        /// Listen keyboard pressed
        /// </summary>
        /// <param name="nCode"></param>
        /// <param name="wParam"></param>
        /// <param name="lParam"></param>
        /// <returns></returns>
        private IntPtr HookCallback(int nCode, IntPtr wParam, IntPtr lParam)
        {
            //event do not be register, do not need to listen
            //if (KeyPressed == null) return (IntPtr)1;
            
            if (nCode >= 0)
            {
                if (wParam == (IntPtr)WindowsKeyboardEvent.WM_KEYDOWN || wParam == (IntPtr)WindowsKeyboardEvent.WM_KEYUP)
                {
                    KBDLLHOOKSTRUCT hookStruct = (KBDLLHOOKSTRUCT)Marshal.PtrToStructure(lParam, typeof(KBDLLHOOKSTRUCT));

                    // Use this to detect if the key press is synthetic (e.g., generated by SendInput or automation tools)
                    bool isSynthetic = hookStruct.dwExtraInfo.ToInt32() == SYNTHETIC_KEY_MARKER;

                    int vkCode = hookStruct.vkCode;
                    Keys key = (Keys)vkCode;
                    KeyState keyState = wParam == (IntPtr)WindowsKeyboardEvent.WM_KEYDOWN ? KeyState.KeyDown : KeyState.KeyUp;

                    CustomKeyMessageEventArgs keyEventArgs;

                    //Copy event
                    if (IsControlPressed() && key == Keys.C)
                    {
                        keyEventArgs = new CustomKeyMessageEventArgs
                        {
                            Command = wParam,
                            Handle = IntPtr.Zero,
                            KeyModifier = Keys.Control,
                            KeyCode = key,
                            KeyType = keyState,
                            Combination = KeyCombination.Copy
                        };
                        if (isSynthetic)
                            keyEventArgs.IsSynthetic = true;

                        KeyPressed?.Invoke(this, keyEventArgs);
                        return Libraries.HookApis.CallNextHookEx(_hookID, nCode, wParam, lParam);
                    } 
                    //Handle keyboard events on form
                    if (WindowsHandle.Count > 0)
                    {
                        var focusedHandles = WindowsHandle.Where(x => IsHandleFocus(x)).ToList();
                        if (focusedHandles.Any())
                        {
                            keyEventArgs = new CustomKeyMessageEventArgs
                            {
                                Command = wParam,
                                Handle = focusedHandles.First(),
                                KeyModifier = Keys.None,
                                KeyCode = key,
                                KeyType = keyState,
                            };
                            KeyPressed?.Invoke(this, keyEventArgs);
                            return (IntPtr)1;
                        }
                    }
                }
            }   
            return HookApis.CallNextHookEx(_hookID, nCode, wParam, lParam);
        }
        private bool IsControlPressed()
        {
            return (KeyboardApis.GetAsyncKeyState((int)WindowsKeyboardEvent.VK_LCONTROL) & 0x8000) != 0 || (KeyboardApis.GetAsyncKeyState((int)WindowsKeyboardEvent.VK_RCONTROL) & 0x8000) != 0;
        }
        private bool IsShiftPressed()
        {
            return (KeyboardApis.GetAsyncKeyState((int)WindowsKeyboardEvent.VK_SHIFT) & 0x8000) != 0;
        }
        private bool IsAltPressed()
        {
            return (KeyboardApis.GetAsyncKeyState((int)WindowsKeyboardEvent.VK_MENU) & 0x8000) != 0 || (KeyboardApis.GetAsyncKeyState((int)WindowsKeyboardEvent.VK_LMENU) & 0x8000) != 0 || (KeyboardApis.GetAsyncKeyState((int)WindowsKeyboardEvent.VK_RMENU) & 0x8000) != 0;
        }
        private bool isLeftWindowKeyPressed()
        {
            return (KeyboardApis.GetAsyncKeyState((int)Keys.LWin) & 0x8000) != 0;
        }
        public string KeyboardEventTostring(IntPtr command, Keys modifier, Keys code, KeyState type)
        {
            return new StringBuilder()
                    .Append((int)command)
                    .Append("|")
                    .Append((int)modifier)
                    .Append("|")
                    .Append((int)code)
                    .Append("|")
                    .Append((int)type).ToString();
        }
        ~GlobalKeyboardHook()
        {
            Dispose(false);
        }
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    lock (_lockObject)
                    {
                        WindowsHandle.Clear();
                    }
                    Stop();
                    _disposed = true;
                }  
            }
        }
    }
}
