<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <TargetFramework>net40</TargetFramework>
	  <LangVersion>8.0</LangVersion>
	  <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\Enums\" />
	<Content Include="Resources\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="1.5.14" />
  </ItemGroup>

</Project>